### PR TITLE
Read item resources

### PR DESCRIPTION
**Pull request by jdgumz**
This PR addresses two tickets in one: retrieving one item resource and retrieving all item resources (#14 and #15 ).

@xynazog your POST action implementation will fit into the `/wishlists/<int:wishlist_id>/items` route controller.  

I needed to make a change to the persistence layer - adding a method to retrieve just a single item, and also adding an exception class for item resources.

### CODE REVIEW

**Comment by nvme5** [comment]
Resolved the merge conflict. 
however @jdgumz - I have a question: 
What if the user doesn't remember the item-id but wants to retrieve the first item in the wishlist?

**Comment by jdgumz** [comment]
@nvme5 this is a fair point - at this time the item is identified by its unique identifier in the catalog or from somewhere else.  We could certainly change this however by having a generic `id` and a more specific `item_id`.

**Comment by nvme5** [comment]
@jdgumz I think that works best, would that be in a separate ticket?

**Comment by jdgumz** [comment]
Yes, we would need to address that as a tech debt or enhancement that is separate from the current ticket.  Of course, that ticket would entail refactoring of items code.

**Comment by nvme5** [comment]
Alright, would you mind creating the ticket? I'll close this issue in that case

**Pull request merged**
